### ISSUE TITLE
Formatting of 5.1 did scheme ABNF is broken

### ISSUE THREAD

**Issue by alanz** [opencreds/did-spec#3]
This appears as a free-flowing paragraph, the original seems to be formatted to expect fixed-layout tags

"
did-reference = did [ "/" did-path ] [ "#" did-fragment ] did = "did:" method ":" specific-idstring method = 1*methodcharmethodchar = %x61-7A / DIGIT specific-idstring = idstring *( ":" idstring ) idstring = 1*idcharidchar = ALPHA / DIGIT / "." / "-" 

"

**Comment by davidlehn** [comment]
Fixed:
https://github.com/opencreds/did-spec/commit/d6947ceab17e67d1078b0fd630c2146ecb094089
https://github.com/opencreds/did-spec/commit/9478f6f200fc9867f4278015c2e1645d27a56912
